apiVersion: v1
kind: ConfigMap
metadata:
  name: "scss-compiler-config"
data:
  image: "{{ .Values.image.repository | default .Values.global.image.repository }}/magda-scss-compiler:{{ .Values.image.tag | default .Values.global.image.tag }}"
  scssVars: {{ .Values.scssVars | quote }}