apiVersion: batch/v1
kind: Job
metadata:
  name: init-scss-compiler
  labels:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      name: "init-scss-compiler"
    spec:
      restartPolicy: OnFailure
      containers:
      - name: init-scss-compiler
        image: "{{ .Values.image.repository | default .Values.global.image.repository }}/magda-scss-compiler:{{ .Values.image.tag | default .Values.global.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy }}
        command: [
            "node",
            "/usr/src/app/component/dist/index.js"
        ]
        env:
        - name: CONTENT_API_URL
          value: "http://content-api/v0"
        - name: USER_ID
          value: {{ .Values.global.defaultAdminUserId }}
        - name: SCSS_VARS
          valueFrom:
            configMapKeyRef:
              name: scss-compiler-config
              key: scssVars
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt-secret
