apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: search-api
spec:
  replicas: {{ .Values.replicas | default 1 }}
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  template:
    metadata:
      labels:
        service: search-api
    spec:
      priorityClassName: magda-8
      containers:
      - name: search-api
        image: {{ template "dockerimage" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy }}
        command:
          - "/app/bin/magda-search-api"
          - "-Dhttp.port=80"
          - "-Dakka.loglevel={{ .Values.global.logLevel }}"
          - "-DelasticSearch.serverUrl=elasticsearch://elasticsearch:9200"
{{- if .Values.datasetsIndexVersion }}
          - "-DelasticSearch.indices.datasets.version={{ .Values.datasetsIndexVersion }}"
{{- end }}
{{- if .Values.regionsIndexVersion }}
          - "-DelasticSearch.indices.regions.version={{ .Values.regionsIndexVersion }}"
{{- end }}
        readinessProbe:
          httpGet:
            path: "/v0/datasets"
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
{{- if .Values.global.enableLivenessProbes }}
        livenessProbe:
          httpGet:
            path: "/v0/datasets"
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
{{- end }}
        ports:
        - containerPort: 80
        resources:
{{ toYaml .Values.resources | indent 10 }}
