apiVersion: v2
name: "magda-core"
description: "A complete solution for managing, publishing and discovering
  government data, private and open. This chart includes all core magda
  modules."
version: "0.0.60-alpha.0"
kubeVersion: ">= 1.14.0-0"
home: "https://github.com/magda-io/magda"
sources: [ "https://github.com/magda-io/magda" ]
dependencies:
  - name: apidocs-server
    version: 0.0.60-alpha.0
    repository: file://../internal-charts/apidocs-server
    tags:
      - all
      - apidocs-server
  - name: authorization-api
    version: 0.0.60-alpha.0
    repository: file://../internal-charts/authorization-api
    tags:
      - all
      - authorization-api
  - name: authorization-db
    version: 0.0.60-alpha.0
    repository: file://../internal-charts/authorization-db
    tags:
      - all
      - authorization-db
  - name: cloud-sql-proxy
    version: 0.0.60-alpha.0
    repository: file://../internal-charts/cloud-sql-proxy
    tags:
      - all
      - cloud-sql-proxy
  - name: combined-db
    version: 0.0.60-alpha.0
    repository: file://../internal-charts/combined-db
    tags:
      - all
      - combined-db
  - name: content-api
    version: 0.0.60-alpha.0
    repository: file://../internal-charts/content-api
    tags:
      - all
      - content-api
  - name: content-db
    version: 0.0.60-alpha.0
    repository: file://../internal-charts/content-db
    tags:
      - all
      - content-db
  - name: correspondence-api
    version: 0.0.60-alpha.0
    repository: file://../internal-charts/correspondence-api
    tags:
      - all
      - correspondence-api
  - name: elasticsearch
    version: 0.0.60-alpha.0
    repository: file://../internal-charts/elasticsearch
    tags:
      - all
      - elasticsearch
  - name: gateway
    version: 0.0.60-alpha.0
    repository: file://../internal-charts/gateway
    tags:
      - all
      - gateway
  - name: indexer
    version: 0.0.60-alpha.0
    repository: file://../internal-charts/indexer
    tags:
      - all
      - indexer
  - name: magda-preview-map
    version: 0.0.58
    alias: preview-map
    repository: https://charts.magda.io
    tags:
      - all
      - preview-map
  - name: registry-api
    version: 0.0.60-alpha.0
    repository: file://../internal-charts/registry-api
    tags:
      - all
      - registry-api
  - name: registry-db
    version: 0.0.60-alpha.0
    repository: file://../internal-charts/registry-db
    tags:
      - all
      - registry-db
  - name: search-api
    version: 0.0.60-alpha.0
    repository: file://../internal-charts/search-api
    tags:
      - all
      - search-api
  - name: search-api-node
    version: 0.0.60-alpha.0
    repository: file://../internal-charts/search-api-node
    tags:
      - search-api-node
  - name: session-db
    version: 0.0.60-alpha.0
    repository: file://../internal-charts/session-db
    tags:
      - all
      - session-db
  - name: web-server
    version: 0.0.60-alpha.0
    repository: file://../internal-charts/web-server
    tags:
      - all
      - web-server
  - name: admin-api
    version: 0.0.60-alpha.0
    repository: file://../internal-charts/admin-api
    tags:
      - all
      - admin-api
  - name: opa
    version: 0.0.60-alpha.0
    repository: file://../internal-charts/opa
    tags:
      - all
      - opa
  - name: storage-api
    version: 0.0.60-alpha.0
    repository: file://../internal-charts/storage-api
    tags:
      - all
      - storage-api
  - name: tenant-api
    version: 0.0.60-alpha.0
    repository: file://../internal-charts/tenant-api
    condition: global.enableMultiTenants
    tags:
      - all
      - tenant-api
  - name: tenant-db
    version: 0.0.60-alpha.0
    repository: file://../internal-charts/tenant-db
    condition: global.enableMultiTenants
    tags:
      - all
      - tenant-db
  - name: openfaas
    version: 5.5.5-magda
    repository: file://../openfaas
    # Users should turn on / off openfaas via this condition var `global.openfaas.enabled` rather than `tags`
    # Due to a limitation of helm, the value of tags is not available in chart template.
    # All openfaas dependents should check this field to decide deployment logic (`tags` unfortunately not available to ).
    # They choose to simply not deploy or prompt an error message via [helm required function](https://helm.sh/docs/howto/charts_tips_and_tricks/#know-your-template-functions)
    condition: global.openfaas.enabled

  # K8s misc
  - name: priorities
    version: 0.0.60-alpha.0
    repository: file://../internal-charts/priorities
    tags:
      - priorities
  - name: ingress
    version: 0.0.60-alpha.0
    repository: file://../internal-charts/ingress
    tags:
      - ingress
