global:
  useCombinedDb: true
  useCloudSql: false
  externalUrl: "http://localhost:6100"
  rollingUpdate:
    maxUnavailable: 0
  exposeNodePorts: false
  image:
    # When we don't specify tag here, .Chart.version will be used --- which is easier for versioning
    # You still can specify a tag here to override the default `.Chart.version` value (e.g. for local debugging)
    # tag: xxxxxxx
    repository: "data61"
    pullPolicy: IfNotPresent
  defaultAdminUserId: "00000000-0000-4000-8000-000000000000"
  logLevel: INFO
  noDbAuth: false
  namespace: default
  gapiIds: []
  enablePriorityClass: false
  # -- the redirection url after the whole authentication process is completed.
  # Authentication Plugins will use this value as default setting.
  # The following query paramaters can be used to supply the authentication result:
  # <ul>
  # <li>result: (string) Compulsory. Possible value: "success" or "failure". </li>
  # <li>errorMessage: (string) Optional. Text message to provide more information on the error to the user. </li>
  # </ul>
  # The default "/sign-in-redirect" url supports an additional `redirectTo` query parameter.
  # If this parameter not presents, user will be redirected further (at frontend) to account page /account.
  # Otherwise, user will redirected to the url sepcified by `redirectTo` query parameter.
  authPluginRedirectUrl: "/sign-in-redirect"
  openfaas:
    # turn on / off openfaas
    # All openfaas dependents should check this field to decide deployment logic (`tags` unfortunately not available to ).
    # They choose to simply not deploy or prompt an error message via [helm required function](https://helm.sh/docs/howto/charts_tips_and_tricks/#know-your-template-functions)
    enabled: true 
    namespacePrefix: ""
    functionNamespace: openfaas-fn  # Default namespace for functions
    mainNamespace: openfaas # Default namespace for gateway and other core modules
    allowAdminOnly: true # Only allow logged-in Admin to access openfaas gateway

openfaas:
  operator: 
    create: true
  serviceType: ClusterIP
  basic_auth: false
  ingress:
    enabled: false
  faasnetes:
    readTimeout: 120s
    writeTimeout: 120s
    imagePullPolicy: IfNotPresent
  gateway:
    scaleFromZero: true
    readTimeout: 125s
    writeTimeout: 125s
    upstreamTimeout: 120s
  faasIdler:
    dryRun: false

# -- (object) Control on/ off of each modules. 
# To turn on/off openfaas, please set value to `global.openfaas.enabled`
# @default -- see default value of each individual tag below.
tags:
  # tags.priorities -- whether or not deploy Magda defined PriorityClass. Useful to schedule different payload on different nodes.
  priorities: true

  # tags.all -- turn on / off all modules
  all: true
  
  # tags.apidocs-server -- turn on / off [apidocs-server](../internal-charts/apidocs-server/README.md)
  apidocs-server: false
  
  # tags.admin-api -- turn on / off [admin-api](../internal-charts/admin-api/README.md)
  admin-api: false
  
  # tags.authorization-api -- turn on / off [authorization-api](../internal-charts/authorization-api/README.md)
  authorization-api: false
  
  # tags.opa -- turn on / off [opa](../internal-charts/opa/README.md)
  opa: false
  
  # tags.authorization-db -- turn on / off [authorization-db](../internal-charts/authorization-db/README.md)
  authorization-db: false
  
  # tags.combined-db -- turn on / off [combined-db](../internal-charts/combined-db/README.md)
  combined-db: false
  
  # tags.content-api -- turn on / off [content-api](../internal-charts/content-api/README.md)
  content-api: false
  
  # tags.content-db -- turn on / off [content-db](../internal-charts/content-db/README.md)
  content-db: false
  
  # tags.correspondence-api -- turn on / off [content-db](../internal-charts/correspondence-api/README.md)
  correspondence-api: false
  
  # tags.elasticsearch -- turn on / off [elasticsearch](../internal-charts/elasticsearch/README.md)
  elasticsearch: false

  # tags.gateway -- turn on / off [gateway](../internal-charts/gateway/README.md)
  gateway: false

  # tags.indexer -- turn on / off [indexer](../internal-charts/indexer/README.md)
  indexer: false

  # tags.preview-map -- turn on / off [preview-map](https://github.com/magda-io/magda-preview-map)
  preview-map: false

  # tags.pregistry-api -- turn on / off [registry-api](../internal-charts/registry-api/README.md)
  registry-api: false

  # tags.registry-db -- turn on / off [registry-db](../internal-charts/registry-db/README.md)
  registry-db: false

  # tags.search-api -- turn on / off [search-api](../internal-charts/search-api/README.md)
  search-api: false

  # tags.search-api-node -- turn on / off [search-api-node](../internal-charts/search-api-node/README.md)
  search-api-node: false

  # tags.session-db -- turn on / off [session-db](../internal-charts/session-db/README.md)
  session-db: false

  # tags.web-server -- turn on / off [web-server](../internal-charts/web-server/README.md)
  web-server: false

  # tags.ingress -- turn on / off [ingress](../internal-charts/ingress/README.md)
  ingress: false

  # tags.storage-api -- turn on / off [storage-api](../internal-charts/storage-api/README.md)
  storage-api: false

  # tags.tenant-api -- turn on / off [tenant-api](../internal-charts/tenant-api/README.md)
  tenant-api: false

  # tags.tenant-db -- turn on / off [tenant-db](../internal-charts/tenant-db/README.md)
  tenant-db: false
