apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  selector:
    matchLabels:
      service: indexer
  template:
    metadata:
      labels:
        service: indexer
    spec:
{{- if and (.Capabilities.APIVersions.Has "scheduling.k8s.io/v1beta1") .Values.global.enablePriorityClass }}
      priorityClassName: magda-7
{{- end }}
      containers:
      - name: indexer
        env:
        - name: S3_SECRET_KEY
          value: dummy
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt-secret
{{- if .Values.global.enableLivenessProbes }}
        livenessProbe:
          httpGet:
            path: /v0/reindex/in-progress
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 10
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        image: {{ template "dockerimage" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy }}
        command: [
            "/app/bin/magda-indexer",
            "-Dhttp.port=80",
            "-Dregistry.webhookUrl=http://indexer/v0/registry-hook",
            "-Dregistry.baseUrl=http://registry-api",
            "-Dregistry.readOnlyBaseUrl=http://registry-api-read-only",
            "-Dindexer.readSnapshots={{ .Values.readSnapshots }}",
            "-Dindexer.makeSnapshots={{ .Values.makeSnapshots }}",
            "-Dakka.loglevel={{ .Values.global.logLevel }}",
            "-DelasticSearch.serverUrl=elasticsearch://elasticsearch:9200",
{{- if .Values.elasticsearch.useGcsSnapshots }}
            "-DelasticSearch.snapshotRepo.type=gcs",
            "-DelasticSearch.snapshotRepo.types.gcs.bucket={{ .Values.elasticsearch.gcsSnapshotBucket }}",
            "-DelasticSearch.snapshotRepo.types.gcs.client={{ .Values.elasticsearch.gcsSnapshotClient }}",
{{- end }}
            "-DelasticSearch.shardCount={{ .Values.elasticsearch.shards }}",
            "-DelasticSearch.replicaCount={{ .Values.elasticsearch.replicas }}",
            "-Dauth.userId={{ .Values.global.defaultAdminUserId }}"
        ]
        volumeMounts:
        - mountPath: /usr/regions
          name: regions
      volumes:
      - name: regions
        hostPath:
          path: /var/regions
