apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: admin-api
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  template:
    metadata:
      labels:
        service: admin-api
    spec:
      priorityClassName: magda-7
      containers:
      - name: admin-api
        image: {{ template "dockerimage" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy }}
        command: [
            "node",
            "/usr/src/app/component/dist/index.js",
            "--listenPort", "80",
            "--dockerRepo", {{ .Values.global.image.repository | quote }},
            "--authApiUrl", "http://authorization-api/v0",
            "--registryApiUrl", "http://registry-api/v0",
            "--imageTag", {{ .Values.image.tag | default .Values.global.image.tag }},
            "--pullPolicy", {{ .Values.global.image.pullPolicy }},
            "--kubernetesApiType", "cluster",
            "--userId", {{ .Values.global.defaultAdminUserId | quote }},
            "--namespace", {{ .Values.global.namespace }}
        ]
{{- if .Values.global.enableLivenessProbes }}
        livenessProbe:
          httpGet:
            path: /v0/healthz
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: NODE_ENV
          value: production
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt-secret
