global:
  useCombinedDb: true
  useCloudSql: false
  externalUrl: https://dev.magda.io
  image:
    pullPolicy: Always
  rollingUpdate:
    maxUnavailable: 1

tags:
  all: true
  ingress: true
  minion-broken-link: true
  minion-linked-data-rating: true
  minion-visualization: true
  minion-format: true

ingress:
  hostname: dev.magda.io
  ingressClass: nginx
  enableTls: true
  useDefaultCertificate: true

gateway:
  ckanRedirectionDomain: "ckan.data.gov.au"
  ckanRedirectionPath: ""
  enableAuthEndpoint: true
  auth:
    facebookClientId: "173073926555600"
    googleClientId: "275237095477-f7ej2gsvbl2alb8bcqcn7r5jk0ur719p.apps.googleusercontent.com"
  cors:
    credentials: true
    origin: true
  helmet:
    frameguard: false
  csp:
    directives:
      scriptSrc:
      - "''self''"
      - "''unsafe-inline''" # For VWO, hopefully we can remove this soon
      - "data:" # Also for VWO
      - browser-update.org
      - dev.visualwebsiteoptimizer.com
      - platform.twitter.com
      - www.googletagmanager.com
      - www.google-analytics.com
      - rum-static.pingdom.net
      - https://cdnjs.cloudflare.com/ajax/libs/rollbar.js/2.4.1/rollbar.min.js
      - https://tagmanager.google.com/debug
      - assets.zendesk.com
      - static.zdassets.com
      - ekr.zdassets.com
      objectSrc:
      - "''none''"
      sandbox: # We run the sandbox because we have to have unsafe-inline, when we remove unsafe inline we should remove this
      - allow-scripts
      - allow-same-origin
      - allow-popups
      - allow-forms
      - allow-popups-to-escape-sandbox
      reportUri: https://sdga.report-uri.com/r/d/csp/enforce

combined-db:
  waleBackup:
    method: WAL
    gsPrefix: "gs://magda-postgres-backups-asia/dev"
    executionTime: 03:00
    googleApplicationCreds:
      secretName: storage-account-credentials
      fileName: TerriaJS-5e042b649f8a.json
  data:
    storage: 250Gi
  antiPreemptibleAffinity: 100

elasticsearch:
  data:
    heapSize: 500m
  backup:
    googleApplicationCreds:
      secretName: storage-account-credentials
      fileName: db-service-account-private-key.json
  antiPreemptibleAffinity: 99

indexer:
  readSnapshots: false
  makeSnapshots: false
  elasticsearch:
    useGcsSnapshots: true
    gcsSnapshotBucket: "magda-es-snapshots-dev"
    gcsSnapshotClient: "default"

web-server:
  fallbackUrl: "https://data.gov.au"

correspondence-api:
  defaultRecipient: "magda-test@googlegroups.com"
  alwaysSendToDefaultRecipient: true
  smtpHostname: "smtp.mailgun.org"
  smtpPort: 2525

minion-broken-link:
  domainWaitTimeConfig:
    data.csiro.au: 5
    data.gov.au: 5
    data.act.gov.au: 30

connectors:
  config:
    - image:
        name: magda-project-open-data-connector
      id: act
      name: ACT Government data.act.gov.au
      sourceUrl: http://www.data.act.gov.au/data.json
    - image:
        name: magda-csw-connector
      id: aims
      name: Australian Institute of Marine Science
      sourceUrl: https://geo.aims.gov.au/geonetwork/srv/eng/csw
      pageSize: 100
    - image:
        name: magda-csw-connector
      id: aodn
      name: Australian Oceans Data Network
      sourceUrl: http://catalogue.aodn.org.au/geonetwork/srv/eng/csw
      pageSize: 100
    - image:
        name: magda-csw-connector
      id: bom
      name: Bureau of Meteorology
      sourceUrl: http://www.bom.gov.au/geonetwork/srv/eng/csw
      pageSize: 100
    - image:
        name: magda-ckan-connector
      id: brisbane
      name: Brisbane City Council
      sourceUrl: https://www.data.brisbane.qld.gov.au/data/
      pageSize: 100
    - image:
        name: magda-project-open-data-connector
      id: hobart
      name: City of Hobart Open Data Portal
      sourceUrl: http://data-1-hobartcc.opendata.arcgis.com/data.json
    - image:
        name: magda-project-open-data-connector
      id: launceston
      name: City of Launceston Open Data
      sourceUrl: https://data-launceston.opendata.arcgis.com/data.json
    - image:
        name: magda-dap-connector
      id: dap
      name: CSIRO
      sourceUrl: https://data.csiro.au/dap/ws/v2/
      pageSize: 100
    - image:
        name: magda-csw-connector
      id: marlin
      name: CSIRO Marlin
      sourceUrl: http://www.marlin.csiro.au/geonetwork/srv/eng/csw
      pageSize: 50
    - image:
        name: magda-ckan-connector
      id: dga
      name: data.gov.au
      sourceUrl: https://data.gov.au/
      pageSize: 1000
      ignoreHarvestSources:
        - "*"
    - image:
        name: magda-csw-connector
      id: environment
      name: Department of the Environment and Energy
      sourceUrl: http://www.environment.gov.au/fed/csw
      pageSize: 100
    - image:
        name: magda-project-open-data-connector
      id: esta
      name: ESTA Open Data
      sourceUrl: http://data-esta000.opendata.arcgis.com/data.json
    - image:
        name: magda-csw-connector
      id: ga
      name: Geoscience Australia
      sourceUrl: http://www.ga.gov.au/geonetwork/srv/en/csw
      pageSize: 100
    - image:
        name: magda-project-open-data-connector
      id: logan
      name: Logan City Council
      sourceUrl: http://data-logancity.opendata.arcgis.com/data.json
    - image:
        name: magda-project-open-data-connector
      id: melbourne
      name: Melbourne Data
      sourceUrl: https://data.melbourne.vic.gov.au/data.json
    - image:
        name: magda-csw-connector
      id: mrt
      name: Mineral Resources Tasmania
      sourceUrl: http://www.mrt.tas.gov.au/web-catalogue/srv/eng/csw
      pageSize: 100
    - image:
        name: magda-project-open-data-connector
      id: moretonbay
      name: Moreton Bay Regional Council Data Portal
      sourceUrl: http://data.moretonbay.qld.gov.au/data.json
    - image:
        name: magda-csw-connector
      id: metoc
      name: 'Navy Meteorology and Oceanography (METOC) '
      sourceUrl: http://www.metoc.gov.au/geonetwork/srv/en/csw
      pageSize: 100
    - image:
        name: magda-csw-connector
      id: neii
      name: National Environmental Information Infrastructure
      sourceUrl: http://neii.bom.gov.au/services/catalogue/csw
      pageSize: 100
    - image:
        name: magda-ckan-connector
      id: nsw
      name: New South Wales Government
      sourceUrl: https://data.nsw.gov.au/data/
      pageSize: 100
    - image:
        name: magda-csw-connector
      id: sdinsw
      name: NSW Land and Property
      sourceUrl: https://sdi.nsw.gov.au/csw
      pageSize: 100
    - image:
        name: magda-csw-connector
      id: qspatial
      name: 'Queensland Spatial Catalogue - QSpatial '
      sourceUrl: "http://qldspatial.information.qld.gov.au/catalogueadmin/csw"
      pageSize: 100
    - image:
        name: magda-ckan-connector
      id: qld
      name: Queensland Government
      sourceUrl: https://data.qld.gov.au/
      pageSize: 100
    - image:
        name: magda-ckan-connector
      id: sa
      name: South Australia Government
      sourceUrl: https://data.sa.gov.au/data/
      pageSize: 100
    - image:
        name: magda-csw-connector
      id: listtas
      name: Tasmania TheList
      sourceUrl: https://data.thelist.tas.gov.au:443/datagn/srv/eng/csw
      pageSize: 100
    - image:
        name: magda-csw-connector
      id: tern
      name: Terrestrial Ecosystem Research Network
      sourceUrl: http://data.auscover.org.au/geonetwork/srv/eng/csw
      pageSize: 100
    - image:
        name: magda-ckan-connector
      id: vic
      name: Victoria Government
      sourceUrl: https://www.data.vic.gov.au/data/
      pageSize: 100
    - image:
        name: magda-ckan-connector
      id: wa
      name: Western Australia Government
      sourceUrl: http://catalogue.beta.data.wa.gov.au/
      pageSize: 100
