global:
  externalUrl: http://minikube.data.gov.au:30100
  rollingUpdate:
    maxUnavailable: 1
  exposeNodePorts: true
  image:
    repository: "localhost:5000/data61"
    tag: "latest"
    pullPolicy: Always
  noDbAuth: true
  useCloudSql: false
  useCombinedDb: true

gateway:
  ckanRedirectionDomain: "ckan.data.gov.au"
  enableAuthEndpoint: true
  cors:
    credentials: true
    origin: true
  auth:
    facebookClientId: "173073926555600"
    googleClientId: "275237095477-f7ej2gsvbl2alb8bcqcn7r5jk0ur719p.apps.googleusercontent.com"
    aafClientUri: "https://rapid.test.aaf.edu.au/jwt/authnrequest/research/IeiWdzrJ47-eSowf3rfLTQ"

registry-api:
  skipAuthorization: true
  
correspondence-api:
  smtpPort: 2525
  defaultRecipient: "alex.gilleran+magda@csiro.it"
  smtpHostname: "smtp.mailgun.org"
  
web-server:
  fallbackUrl: "https://data.gov.au"

connectors:
  includeCronJobs: false
  config:
    - image:
        name: "magda-ckan-connector"
      id: dga
      name: "data.gov.au"
      sourceUrl: "https://data.gov.au/"
      pageSize: 1000
      schedule: "0 * * * *"
      ignoreHarvestSources: ["*"]