production: false
image: {}
client:
  pluginsInstall: ""
  heapSize: "256m"
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 500Mi
    limits:
      cpu: 100m
data:
  storage: 200Gi
  pluginsInstall: ""
  heapSize: "512m"
  resources:
    requests:
      cpu: 200m
      memory: 1000Mi
    limits:
      cpu: 500m
master:
  pluginsInstall: ""
  resources:
    requests:
      cpu: 50m
      memory: 900Mi
    limits:
      cpu: 100m
backup:
  googleApplicationCreds: {}