apiVersion: v1
kind: Service
metadata:
  name: apidocs-server
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
{{- if .Values.global.exposeNodePorts }}
    nodePort: 30118
  type: NodePort
{{- end }}
  selector:
    service: apidocs-server
