image: {}
auth: {}
service:
  type: NodePort
  externalPort: 80
  internalPort: 80
  
autoscaler:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

enableAuthEndpoint: false
enableWebAccessControl: false

helmet:
  frameguard: false

resources:
  requests:
    cpu: 50m
    memory: 40Mi
  limits:
    cpu: 200m

routes:
  search:
    to: http://search-api/v0
  registry:
    to: http://registry-api-read-only/v0
  registry-auth:
    to: http://registry-api/v0
    auth: true
  auth:
    to: http://authorization-api/v0/public
    auth: true
  admin:
    to: http://admin-api/v0
    auth: true
  content:
    to: http://content-api/v0
  correspondence:
    to: http://correspondence-api/v0/public
  apidocs:
    to: http://apidocs-server/
    redirectTrailingSlash: true
helmet: {}

csp:
  browserSniff: false
  directives:
    scriptSrc:
    - "''self''"
    objectSrc:
    - "''none''"

cors: {}
