image: {}
resources:
  requests:
    cpu: 10m
    memory: 30Mi
  limits:
    cpu: 50m

# -- specify bucket region
# @default -- "unspecified-region"
minioRegion: ""

minio:
  host: "minio"
  port: 9000
  nameOverride: "magda-minio"
  fullnameOverride: "magda-minio"
  existingSecret: "storage-secrets"
  resources:
    requests:
      memory: 256Mi
  persistence:
    size: 10Gi
  DeploymentUpdate:
    type: Recreate

