{{- if .Values.global.useCloudSql }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloud-sql-proxy
spec:
  replicas: {{ .Values.replicas | default 1 }}
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  template:
    metadata:
      labels:
        service: cloud-sql-proxy
    spec:
      priorityClassName: magda-9
      containers:
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances={{ .Values.instanceConnectionName }}=tcp:0.0.0.0:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
{{- if .Values.global.enableLivenessProbes }}
        livenessProbe:
          exec:
            command: ["nc", "-z", "127.0.0.1", "5432"]
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      - name: cloudsql
        emptyDir:
{{- end }}
