apiVersion: v2
name: "magda"
description: "A complete solution for managing, publishing and discovering
  government data, private and open. This chart includes the magda default
  deployment."
version: "0.0.60-alpha.0"
kubeVersion: ">= 1.14.0-0"
home: "https://github.com/magda-io/magda"
sources: [ "https://github.com/magda-io/magda" ]
dependencies:
  - name: magda-core
    version: 0.0.60-alpha.0
    repository: file://../magda-core
  # magda-core chart is always enabled.
  # Thus, no tags or condition are required.
  # You should set its sub-chart to enabled or not.
  - name: magda-function-history-report
    version: 0.0.57-0
    repository: https://charts.magda.io
    tags:
      - all
      - magda-function-history-report

  - name: magda-minion-broken-link
    alias: minion-broken-link
    version: 0.0.57-0
    repository: https://charts.magda.io
    tags:
      - minions
      - minion-broken-link

  - name: magda-minion-format
    alias: minion-format
    version: 0.0.57-0
    repository: https://charts.magda.io
    tags:
      - minions
      - minion-format

  - name: magda-minion-linked-data-rating
    alias: minion-linked-data-rating
    version: 0.0.57-0
    repository: https://charts.magda.io
    tags:
      - minions
      - minion-linked-data-rating

  - name: magda-minion-visualization
    alias: minion-visualization
    version: 0.0.57-0
    repository: https://charts.magda.io
    tags:
      - minions
      - minion-visualization

  - name: magda-minion-ckan-exporter
    version: 0.0.57-0
    repository: https://charts.magda.io
    tags:
      - minion-ckan-exporter

  - name: magda-ckan-connector
    version: 0.0.57-0
    alias: ckan-connector-functions
    repository: https://charts.magda.io
    tags:
      - all
      - url-processors
      - ckan-connector-functions

  - name: magda-function-esri-url-processor
    version: 0.0.57-0
    repository: https://charts.magda.io
    tags:
      - all
      - url-processors
      - magda-function-esri-url-processor
