image: {}
  #repository: data61/
  #tag: latest
  # pullPolicy: Always
data:
  storage: 200Gi
  #storageClass: "ssd"
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
autoVacuum:
  enable: true
  # -- auto vacuum cronjob schedule string. specified using unix-cron format (in UTC timezone by default).
  # @default -- "0 19 * * *": 7:00PM UTC timezone (5:00AM in AEST Sydney timezone) daily
  schedule: "0 19 * * *" 